<?xml version="1.0" encoding="UTF-8"?><testrun name="FtpTest" project="shop-manager-web" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="com.shop.controller.FtpTest" time="0.122">
    <testcase name="ftpClient" classname="com.shop.controller.FtpTest" time="0.122">
      <error>java.net.SocketException: Software caused connection abort: recv failed&#13;
	at java.net.SocketInputStream.socketRead0(Native Method)&#13;
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)&#13;
	at java.net.SocketInputStream.read(SocketInputStream.java:171)&#13;
	at java.net.SocketInputStream.read(SocketInputStream.java:141)&#13;
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)&#13;
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)&#13;
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)&#13;
	at java.io.InputStreamReader.read(InputStreamReader.java:184)&#13;
	at java.io.BufferedReader.fill(BufferedReader.java:161)&#13;
	at java.io.BufferedReader.read(BufferedReader.java:182)&#13;
	at org.apache.commons.net.io.CRLFLineReader.readLine(CRLFLineReader.java:58)&#13;
	at org.apache.commons.net.ftp.FTP.__getReply(FTP.java:314)&#13;
	at org.apache.commons.net.ftp.FTP.__getReply(FTP.java:294)&#13;
	at org.apache.commons.net.ftp.FTP.sendCommand(FTP.java:483)&#13;
	at org.apache.commons.net.ftp.FTP.sendCommand(FTP.java:608)&#13;
	at org.apache.commons.net.ftp.FTP.port(FTP.java:932)&#13;
	at org.apache.commons.net.ftp.FTPClient._openDataConnection_(FTPClient.java:812)&#13;
	at org.apache.commons.net.ftp.FTPClient._storeFile(FTPClient.java:633)&#13;
	at org.apache.commons.net.ftp.FTPClient.__storeFile(FTPClient.java:624)&#13;
	at org.apache.commons.net.ftp.FTPClient.storeFile(FTPClient.java:1976)&#13;
	at com.shop.controller.FtpTest.ftpClient(FtpTest.java:24)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:498)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
